# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4

language: objective-c

before_install:
 - pod install --project-directory=Example
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- xcodebuild -workspace Example/AppmazoKit.xcworkspace -scheme AppmazoKit-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
- pod lib lint --quick
